// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: .proto

package pvz

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllPvzsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPvzsRequest) Reset() {
	*x = GetAllPvzsRequest{}
	mi := &file___proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPvzsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPvzsRequest) ProtoMessage() {}

func (x *GetAllPvzsRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPvzsRequest.ProtoReflect.Descriptor instead.
func (*GetAllPvzsRequest) Descriptor() ([]byte, []int) {
	return file___proto_rawDescGZIP(), []int{0}
}

type Pvz struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RegistrationDate string                 `protobuf:"bytes,2,opt,name=registration_date,json=registrationDate,proto3" json:"registration_date,omitempty"`
	City             string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Pvz) Reset() {
	*x = Pvz{}
	mi := &file___proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pvz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pvz) ProtoMessage() {}

func (x *Pvz) ProtoReflect() protoreflect.Message {
	mi := &file___proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pvz.ProtoReflect.Descriptor instead.
func (*Pvz) Descriptor() ([]byte, []int) {
	return file___proto_rawDescGZIP(), []int{1}
}

func (x *Pvz) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pvz) GetRegistrationDate() string {
	if x != nil {
		return x.RegistrationDate
	}
	return ""
}

func (x *Pvz) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type GetAllPvzsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pvzs          []*Pvz                 `protobuf:"bytes,1,rep,name=pvzs,proto3" json:"pvzs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPvzsResponse) Reset() {
	*x = GetAllPvzsResponse{}
	mi := &file___proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPvzsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPvzsResponse) ProtoMessage() {}

func (x *GetAllPvzsResponse) ProtoReflect() protoreflect.Message {
	mi := &file___proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPvzsResponse.ProtoReflect.Descriptor instead.
func (*GetAllPvzsResponse) Descriptor() ([]byte, []int) {
	return file___proto_rawDescGZIP(), []int{2}
}

func (x *GetAllPvzsResponse) GetPvzs() []*Pvz {
	if x != nil {
		return x.Pvzs
	}
	return nil
}

var File___proto protoreflect.FileDescriptor

const file___proto_rawDesc = "" +
	"\n" +
	"\x06.proto\x12\x04grpc\"\x13\n" +
	"\x11GetAllPvzsRequest\"V\n" +
	"\x03Pvz\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x11registration_date\x18\x02 \x01(\tR\x10registrationDate\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\"3\n" +
	"\x12GetAllPvzsResponse\x12\x1d\n" +
	"\x04pvzs\x18\x01 \x03(\v2\t.grpc.PvzR\x04pvzs2M\n" +
	"\n" +
	"PvzService\x12?\n" +
	"\n" +
	"GetAllPvzs\x12\x17.grpc.GetAllPvzsRequest\x1a\x18.grpc.GetAllPvzsResponseB\x06Z\x04/pvzb\x06proto3"

var (
	file___proto_rawDescOnce sync.Once
	file___proto_rawDescData []byte
)

func file___proto_rawDescGZIP() []byte {
	file___proto_rawDescOnce.Do(func() {
		file___proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file___proto_rawDesc), len(file___proto_rawDesc)))
	})
	return file___proto_rawDescData
}

var file___proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file___proto_goTypes = []any{
	(*GetAllPvzsRequest)(nil),  // 0: grpc.GetAllPvzsRequest
	(*Pvz)(nil),                // 1: grpc.Pvz
	(*GetAllPvzsResponse)(nil), // 2: grpc.GetAllPvzsResponse
}
var file___proto_depIdxs = []int32{
	1, // 0: grpc.GetAllPvzsResponse.pvzs:type_name -> grpc.Pvz
	0, // 1: grpc.PvzService.GetAllPvzs:input_type -> grpc.GetAllPvzsRequest
	2, // 2: grpc.PvzService.GetAllPvzs:output_type -> grpc.GetAllPvzsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file___proto_init() }
func file___proto_init() {
	if File___proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file___proto_rawDesc), len(file___proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file___proto_goTypes,
		DependencyIndexes: file___proto_depIdxs,
		MessageInfos:      file___proto_msgTypes,
	}.Build()
	File___proto = out.File
	file___proto_goTypes = nil
	file___proto_depIdxs = nil
}
