// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: .proto

package pvz

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PvzService_GetAllPvzs_FullMethodName = "/grpc.PvzService/GetAllPvzs"
)

// PvzServiceClient is the client API for PvzService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PvzServiceClient interface {
	GetAllPvzs(ctx context.Context, in *GetAllPvzsRequest, opts ...grpc.CallOption) (*GetAllPvzsResponse, error)
}

type pvzServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPvzServiceClient(cc grpc.ClientConnInterface) PvzServiceClient {
	return &pvzServiceClient{cc}
}

func (c *pvzServiceClient) GetAllPvzs(ctx context.Context, in *GetAllPvzsRequest, opts ...grpc.CallOption) (*GetAllPvzsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllPvzsResponse)
	err := c.cc.Invoke(ctx, PvzService_GetAllPvzs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PvzServiceServer is the server API for PvzService service.
// All implementations must embed UnimplementedPvzServiceServer
// for forward compatibility.
type PvzServiceServer interface {
	GetAllPvzs(context.Context, *GetAllPvzsRequest) (*GetAllPvzsResponse, error)
	mustEmbedUnimplementedPvzServiceServer()
}

// UnimplementedPvzServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPvzServiceServer struct{}

func (UnimplementedPvzServiceServer) GetAllPvzs(context.Context, *GetAllPvzsRequest) (*GetAllPvzsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPvzs not implemented")
}
func (UnimplementedPvzServiceServer) mustEmbedUnimplementedPvzServiceServer() {}
func (UnimplementedPvzServiceServer) testEmbeddedByValue()                    {}

// UnsafePvzServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PvzServiceServer will
// result in compilation errors.
type UnsafePvzServiceServer interface {
	mustEmbedUnimplementedPvzServiceServer()
}

func RegisterPvzServiceServer(s grpc.ServiceRegistrar, srv PvzServiceServer) {
	// If the following call pancis, it indicates UnimplementedPvzServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PvzService_ServiceDesc, srv)
}

func _PvzService_GetAllPvzs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllPvzsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PvzServiceServer).GetAllPvzs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PvzService_GetAllPvzs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PvzServiceServer).GetAllPvzs(ctx, req.(*GetAllPvzsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PvzService_ServiceDesc is the grpc.ServiceDesc for PvzService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PvzService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.PvzService",
	HandlerType: (*PvzServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllPvzs",
			Handler:    _PvzService_GetAllPvzs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: ".proto",
}
